name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-dockerfile-list:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3

      - name: Generate list of Dockerfiles
        run: |
          echo '{"dockerfiles":[' > dockerfile_list.json
          find . -type f \( -name "Dockerfile" -o -name "*.Dockerfile" \) -printf '"%p", ' >> dockerfile_list.json
          echo 'null]}' >> dockerfile_list.json
          sed -i '$ s/, null]/]/' dockerfile_list.json # Correctly formats the JSON to remove the last comma
      - name: Print dockerfile_list.json
        run: cat dockerfile_list.json
      - name: Set output
        id: set-matrix
        run: |
          MATRIX=$(jq -c '{dockerfiles: [.dockerfiles[] | select(. != null)]}' dockerfile_list.json)
          echo "::set-output name=matrix::${MATRIX}"
          echo "MATRIX_JSON=${MATRIX}" >> $GITHUB_ENV

  build:
    needs: generate-dockerfile-list
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dockerfile: ${{fromJson(needs.generate-dockerfile-list.outputs.matrix).dockerfiles}}
    steps:
      - uses: actions/checkout@v3

      - name: Set project name
        run: echo "PROJECT_NAME=$(echo $GITHUB_REPOSITORY | sed 's|.*/||')" >> $GITHUB_ENV

      - name: Build and Push Docker image
        run: |
          DOCKERFILE_PATH="${{ matrix.dockerfile }}"
          TAG=$(echo "$DOCKERFILE_PATH" | awk -F/ '{print $(NF-1)}')
          IMAGE_NAME="${{ secrets.DOCKERHUB_LOGIN }}/FDS:$TAG"
          echo "------------------- TAG = $TAG-------------------"
          
          echo "Building Docker image: $IMAGE_NAME"
          docker build . --file "$DOCKERFILE_PATH" --tag "$IMAGE_NAME"
          
          echo "Logging in to Docker Hub..."
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_LOGIN }} --password-stdin
          
          echo "Pushing Docker image: $IMAGE_NAME"
          docker push "$IMAGE_NAME"
